-- 1. Create Tables
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  username TEXT UNIQUE,
  age INTEGER,
  gender TEXT CHECK (gender IN ('male', 'female', 'other')),
  avatar_url TEXT,
  role TEXT CHECK (role IN ('user', 'admin')) DEFAULT 'user',
  credit_balance INTEGER DEFAULT 100,
  total_spent NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE public.tools (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_name TEXT NOT NULL,
  description TEXT,
  credit_cost INTEGER DEFAULT 0,
  enabled BOOLEAN DEFAULT true,
  category TEXT DEFAULT 'General',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE public.tool_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  tool_id BIGINT REFERENCES public.tools(id) ON DELETE CASCADE NOT NULL,
  credits_spent INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE public.credit_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount INTEGER NOT NULL,
  type TEXT CHECK (type IN ('add', 'deduct', 'set')) NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tool_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_history ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies
-- Profiles: Users can read their own profile. Admins can read all.
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update profiles" ON public.profiles FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Tools: Everyone can read enabled tools. Admins can read/write all.
CREATE POLICY "Anyone can view tools" ON public.tools FOR SELECT USING (true);
CREATE POLICY "Admins can insert tools" ON public.tools FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update tools" ON public.tools FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Tool Usage & Credit History: Users can view their own. Admins can view all.
CREATE POLICY "Users can view own usage" ON public.tool_usage FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all usage" ON public.tool_usage FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Users can view own credit history" ON public.credit_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all credit history" ON public.credit_history FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 4. Trigger to create profile on signup and assign admin roles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  assigned_role TEXT;
BEGIN
  IF NEW.email IN ('nadiaparveen1526@gmail.com', 'tuijbialnajah@gmail.com', 'tuijbialnajah0@gmail.com', 'pintrestk11@gmail.com') THEN
    assigned_role := 'admin';
  ELSE
    assigned_role := 'user';
  END IF;

  INSERT INTO public.profiles (id, email, role, credit_balance, total_spent, avatar_url)
  VALUES (NEW.id, NEW.email, assigned_role, 100, 0, 'https://api.dicebear.com/7.x/lorelei/svg?seed=' || NEW.id);
  
  INSERT INTO public.credit_history (user_id, amount, type, reason)
  VALUES (NEW.id, 100, 'add', 'Initial signup bonus');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. Rank and Reward Functions
-- Function to calculate Rank Name based on EXP
CREATE OR REPLACE FUNCTION public.get_rank_name(p_exp NUMERIC)
RETURNS TEXT AS $$
BEGIN
  RETURN CASE
    WHEN p_exp >= 10000000 THEN 'Void'
    WHEN p_exp >= 750000   THEN 'Singularity'
    WHEN p_exp >= 250000   THEN 'Omni'
    WHEN p_exp >= 100000   THEN 'Cosmic'
    WHEN p_exp >= 50000    THEN 'Eternal'
    WHEN p_exp >= 20000    THEN 'Astral'
    WHEN p_exp >= 15000    THEN 'Celestial'
    WHEN p_exp >= 11111    THEN 'Mythic'
    WHEN p_exp >= 8000     THEN 'Tyrant'
    WHEN p_exp >= 6000     THEN 'Overlord'
    WHEN p_exp >= 4500     THEN 'Abyss'
    WHEN p_exp >= 3200     THEN 'Demon'
    WHEN p_exp >= 2400     THEN 'Wraith'
    WHEN p_exp >= 1700     THEN 'Phantom'
    WHEN p_exp >= 1200     THEN 'Reaper'
    WHEN p_exp >= 800      THEN 'Slayer'
    WHEN p_exp >= 500      THEN 'Hunter'
    WHEN p_exp >= 250      THEN 'Claw'
    WHEN p_exp >= 100      THEN 'Fang'
    ELSE 'Ash'
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Function to calculate Rank Category
CREATE OR REPLACE FUNCTION public.get_rank_category(p_exp NUMERIC)
RETURNS TEXT AS $$
BEGIN
  RETURN CASE
    WHEN p_exp >= 50000 THEN 'Cosmic'
    WHEN p_exp >= 6000  THEN 'Rulers & Divine'
    WHEN p_exp >= 1200  THEN 'Supernatural'
    ELSE 'Hunter / Warrior'
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Function to calculate Rank Reward based on EXP
CREATE OR REPLACE FUNCTION public.get_rank_reward(p_exp NUMERIC)
RETURNS INTEGER AS $$
BEGIN
  RETURN CASE
    WHEN p_exp >= 10000000 THEN 23376 -- Void
    WHEN p_exp >= 750000   THEN 15584 -- Singularity
    WHEN p_exp >= 250000   THEN 10389 -- Omni
    WHEN p_exp >= 100000   THEN 6926  -- Cosmic
    WHEN p_exp >= 50000    THEN 4617  -- Eternal
    WHEN p_exp >= 20000    THEN 3078  -- Astral
    WHEN p_exp >= 15000    THEN 2052  -- Celestial
    WHEN p_exp >= 11111    THEN 1368  -- Mythic
    WHEN p_exp >= 8000     THEN 912   -- Tyrant
    WHEN p_exp >= 6000     THEN 608   -- Overlord
    WHEN p_exp >= 4500     THEN 405   -- Abyss
    WHEN p_exp >= 3200     THEN 270   -- Demon
    WHEN p_exp >= 2400     THEN 180   -- Wraith
    WHEN p_exp >= 1700     THEN 120   -- Phantom
    WHEN p_exp >= 1200     THEN 80    -- Reaper
    WHEN p_exp >= 800      THEN 53    -- Slayer
    WHEN p_exp >= 500      THEN 35    -- Hunter
    WHEN p_exp >= 250      THEN 23    -- Claw
    WHEN p_exp >= 100      THEN 15    -- Fang
    ELSE 10                           -- Ash
  END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Function to distribute rewards to all users
CREATE OR REPLACE FUNCTION public.distribute_rank_rewards()
RETURNS void AS $$
BEGIN
  UPDATE public.profiles
  SET credit_balance = credit_balance + public.get_rank_reward(total_spent / 10);
END;
$$ LANGUAGE plpgsql;

-- 6. Secure RPC for executing tools (deducts credits)
CREATE OR REPLACE FUNCTION public.execute_tool(p_tool_id BIGINT)
RETURNS JSON AS $$
DECLARE
  v_user_id UUID;
  v_tool RECORD;
  v_balance INTEGER;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT * INTO v_tool FROM public.tools WHERE id = p_tool_id AND enabled = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tool not found or disabled';
  END IF;

  SELECT credit_balance INTO v_balance FROM public.profiles WHERE id = v_user_id;
  IF v_balance < v_tool.credit_cost THEN
    RAISE EXCEPTION 'Insufficient credits';
  END IF;

  -- Deduct credits and update total spent
  UPDATE public.profiles 
  SET 
    credit_balance = credit_balance - v_tool.credit_cost,
    total_spent = total_spent + v_tool.credit_cost
  WHERE id = v_user_id;
  
  -- Log usage
  INSERT INTO public.tool_usage (user_id, tool_id, credits_spent) VALUES (v_user_id, p_tool_id, v_tool.credit_cost);
  
  -- Log history
  INSERT INTO public.credit_history (user_id, amount, type, reason) VALUES (v_user_id, v_tool.credit_cost, 'deduct', 'Used tool: ' || v_tool.tool_name);

  RETURN json_build_object('message', 'Successfully executed ' || v_tool.tool_name, 'result', 'Mock result for ' || v_tool.tool_name);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Secure RPC for admins to update credits
CREATE OR REPLACE FUNCTION public.admin_update_credits(p_user_id UUID, p_amount INTEGER, p_action TEXT, p_reason TEXT)
RETURNS JSON AS $$
DECLARE
  v_admin_role TEXT;
  v_current_balance INTEGER;
  v_new_balance INTEGER;
  v_diff INTEGER;
  v_type TEXT;
BEGIN
  SELECT role INTO v_admin_role FROM public.profiles WHERE id = auth.uid();
  IF v_admin_role != 'admin' THEN
    RAISE EXCEPTION 'Admin access required';
  END IF;

  SELECT credit_balance INTO v_current_balance FROM public.profiles WHERE id = p_user_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'User not found';
  END IF;

  IF p_action = 'add' THEN
    v_new_balance := v_current_balance + p_amount;
    v_diff := p_amount;
    v_type := 'add';
  ELSIF p_action = 'deduct' THEN
    v_new_balance := GREATEST(0, v_current_balance - p_amount);
    v_diff := v_current_balance - v_new_balance;
    v_type := 'deduct';
  ELSIF p_action = 'set' THEN
    v_new_balance := p_amount;
    v_diff := ABS(p_amount - v_current_balance);
    IF p_amount > v_current_balance THEN
      v_type := 'add';
    ELSE
      v_type := 'deduct';
    END IF;
  ELSE
    RAISE EXCEPTION 'Invalid action';
  END IF;

  UPDATE public.profiles SET credit_balance = v_new_balance WHERE id = p_user_id;
  
  IF v_diff > 0 THEN
    INSERT INTO public.credit_history (user_id, amount, type, reason) VALUES (p_user_id, v_diff, v_type, COALESCE(p_reason, 'Admin adjustment'));
  END IF;

  RETURN json_build_object('message', 'Credits updated successfully', 'newBalance', v_new_balance);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Leaderboard View (Hides emails)
CREATE OR REPLACE VIEW public.leaderboard AS
SELECT 
  username,
  age,
  total_spent,
  credit_balance,
  avatar_url,
  created_at
FROM public.profiles
WHERE username IS NOT NULL;

-- Grant access to the view
GRANT SELECT ON public.leaderboard TO anon, authenticated;

-- 8. Seed initial tools
INSERT INTO public.tools (tool_name, description, credit_cost, enabled, category) VALUES
  ('AI Text Generator', 'Generate creative text using AI.', 10, true, 'AI'),
  ('Image Upscaler', 'Upscale and enhance image resolution up to 8x.', 10, true, 'Image'),
  ('Image Resizer', 'Resize images quickly and easily.', 2, true, 'Image'),
  ('PDF Converter', 'Convert documents to PDF format.', 5, true, 'File'),
  ('Code Formatter', 'Format your code snippets beautifully.', 1, true, 'Developer'),
  ('SEO Analyzer', 'Analyze your website for SEO improvements.', 15, true, 'Marketing');
