-- Supabase Setup SQL
-- Run this in your Supabase SQL Editor

-- 1. Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    credit_balance INTEGER DEFAULT 100,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create tools table
CREATE TABLE IF NOT EXISTS public.tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name TEXT NOT NULL,
    description TEXT,
    credit_cost INTEGER DEFAULT 0,
    category TEXT DEFAULT 'General',
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create credit_transactions table
CREATE TABLE IF NOT EXISTS public.credit_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    amount INTEGER NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('add', 'deduct', 'set')),
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_transactions ENABLE ROW LEVEL SECURITY;

-- 5. Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- 6. Automatic Profile Creation Trigger
-- This ensures a profile is created even if the client-side insert fails
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, credit_balance)
  VALUES (
    new.id, 
    new.email, 
    CASE 
      WHEN new.email IN ('tuijbialnajah0@gmail.com', 'nadiaparveen1526@gmail.com', 'tuijbialnajah@gmail.com', 'pintrestk11@gmail.com', 'kamranaliarts69@gmail.com') THEN 'admin' 
      ELSE 'user' 
    END, 
    100
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to run the function on every signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. Tools Policies
CREATE POLICY "Tools are viewable by everyone." ON public.tools
    FOR SELECT USING (true);

CREATE POLICY "Only admins can modify tools." ON public.tools
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- 7. Credit Transactions Policies
CREATE POLICY "Users can view own transactions." ON public.credit_transactions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Only admins can view all transactions." ON public.credit_transactions
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- 8. RPC Functions

-- Drop existing functions first to avoid return type change errors
DROP FUNCTION IF EXISTS public.admin_update_credits(UUID, INTEGER, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.execute_tool(BIGINT);

-- Function to update user credits (Admin only)
CREATE OR REPLACE FUNCTION public.admin_update_credits(
    p_user_id UUID,
    p_amount INTEGER,
    p_action TEXT,
    p_reason TEXT DEFAULT 'Admin adjustment'
)
RETURNS VOID AS $$
DECLARE
    v_current_balance INTEGER;
    v_new_balance INTEGER;
BEGIN
    -- Check if caller is admin
    IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin') THEN
        RAISE EXCEPTION 'Unauthorized: Only admins can update credits.';
    END IF;

    -- Get current balance
    SELECT credit_balance INTO v_current_balance FROM public.profiles WHERE id = p_user_id;

    -- Calculate new balance
    IF p_action = 'add' THEN
        v_new_balance := v_current_balance + p_amount;
    ELSIF p_action = 'deduct' THEN
        v_new_balance := v_current_balance - p_amount;
    ELSIF p_action = 'set' THEN
        v_new_balance := p_amount;
    ELSE
        RAISE EXCEPTION 'Invalid action: %', p_action;
    END IF;

    -- Update profile
    UPDATE public.profiles
    SET credit_balance = v_new_balance
    WHERE id = p_user_id;

    -- Log transaction
    INSERT INTO public.credit_transactions (user_id, amount, action, reason)
    VALUES (p_user_id, p_amount, p_action, p_reason);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to execute a tool (Deducts credits)
CREATE OR REPLACE FUNCTION public.execute_tool(p_tool_id BIGINT)
RETURNS JSON AS $$
DECLARE
    v_cost INTEGER;
    v_balance INTEGER;
    v_tool_name TEXT;
    v_is_admin BOOLEAN;
BEGIN
    -- Check if user is admin
    SELECT role = 'admin' INTO v_is_admin FROM public.profiles WHERE id = auth.uid();

    -- Get tool info
    SELECT tool_name, credit_cost INTO v_tool_name, v_cost FROM public.tools WHERE id = p_tool_id AND enabled = true;
    
    IF v_tool_name IS NULL THEN
        RAISE EXCEPTION 'Tool not found or disabled.';
    END IF;

    -- If not admin, check and deduct credits
    IF NOT v_is_admin THEN
        SELECT credit_balance INTO v_balance FROM public.profiles WHERE id = auth.uid();
        
        IF v_balance < v_cost THEN
            RAISE EXCEPTION 'Insufficient credits.';
        END IF;

        -- Deduct credits
        UPDATE public.profiles
        SET credit_balance = v_balance - v_cost
        WHERE id = auth.uid();

        -- Log transaction
        INSERT INTO public.credit_transactions (user_id, amount, action, reason)
        VALUES (auth.uid(), v_cost, 'deduct', 'Executed tool: ' || v_tool_name);
    END IF;

    RETURN json_build_object(
        'status', 'success',
        'message', 'Tool ' || v_tool_name || ' executed successfully!',
        'cost', CASE WHEN v_is_admin THEN 0 ELSE v_cost END
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9. Initial Data (Optional)
INSERT INTO public.tools (tool_name, description, credit_cost, category)
VALUES 
('Background Remover', 'AI-powered tool to remove backgrounds from images.', 10, 'Media'),
('Image Generator', 'AI-powered image generation tool.', 10, 'Creative'),
('Text Summarizer', 'Summarize long articles instantly.', 5, 'Productivity'),
('Code Helper', 'Debug and optimize your code snippets.', 15, 'Developer');
